name: Deploy Angular Frontend to Bare Metal

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci

    - name: Build Angular app
      run: npm run build -- --configuration production

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: frontend-package
        path: dist/**

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: frontend-package
        path: .

    - name: Inspect workspace
      run: ls -R .

    - name: Create release folder on server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 2222
        script: |
          rm -rf /home/adi/releases/frontend-${{ github.run_number }}
          mkdir -p /home/adi/releases/frontend-${{ github.run_number }}

    - name: Create tarball from browser folder
      run: |
        tar -czf frontend.tar.gz -C browser .

    - name: Upload tarball to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 2222
        source: "frontend.tar.gz"
        target: "/home/adi/releases/frontend-${{ github.run_number }}"

    - name: Extract tarball on server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 2222
        script: |
          cd /home/adi/releases/frontend-${{ github.run_number }}
          tar -xzf frontend.tar.gz
          rm frontend.tar.gz

    - name: Update symlink for frontend
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 2222
        script: |
          sudo rm -rf /var/www/qrfe
          sudo ln -sfn /home/adi/releases/frontend-${{ github.run_number }} /var/www/qrfe

    - name: Restart nginx
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 2222
        script: |
          sudo systemctl reload nginx
